# Site settings
title: "Liam's Blog"
subtitle: "陈亮亮"
description: "一个神奇的网站"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://helloyoubeautifulthing.net"
page_no_title: "No title" # 文章无标题时默认显示内容
beian: # "备案号"
email: email@yourdomain.com

# Build settings
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
plugins: [jekyll-paginate]
permalink: pretty

# Pageinate settings
paginate: 5 # 分页大小
paginate_path: ":num"

# Search settings
baidu_search: true
google_search: # true

# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'toxic-07'

# Menu settings
menu:
  - page: 首页
    directory: .
    #icon: icon-home
  - page: 归档
    directory: archives/
    #icon: icon-archive
  - page: 关于
    directory: about/
    #icon: icon-about
  #- page: 历史
  #  directory: history/
  #  icon: icon-history
  - page: 订阅
    directory: feed.xml
    #icon: icon-rss

# Link settings
links: # 友情链接
  - title: JSON 在线解析/格式化 - JsonTool.cn
    url: https://jsontool.cn
  #- title: site-name2
  #  url: http://www.example2.com/
  #- title: site-name3
  #  url: http://www.example3.com/
